spring:
  data:
    mongodb:
      uri: mongodb+srv://${USER_DB}:${PASSWORD_DB}@webfluxclustercourse.q0fm1ic.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority&appName=webFluxClusterCourse